debug: false
server:
  servlet:
    context-path: /api
spring:
  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: https://cognito-idp.eu-central-1.amazonaws.com/eu-central-1_EyHbp5FDG
